//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruncatedJsonRepro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TruncatedJsonRepro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;SectionData&quot;:{&quot;SectionId&quot;:&quot;B669F6A8ED5A07E6!1701&quot;,&quot;SectionName&quot;:&quot;IFTTT&quot;,&quot;CreatedTime&quot;:&quot;2016-02-04T23:24:15.46Z&quot;,&quot;CreatedBy&quot;:&quot;でぷ卤解onecaptest&quot;,&quot;NotebookId&quot;:&quot;B669F6A8ED5A07E6!1675&quot;,&quot;ParentId&quot;:&quot;B669F6A8ED5A07E6!1675&quot;,&quot;LastModifiedTime&quot;:&quot;2016-05-16T23:47:49.01Z&quot;,&quot;LastModifiedBy&quot;:&quot;でぷ卤解onecaptest&quot;,&quot;Links&quot;:{&quot;DavUrl&quot;:{&quot;Href&quot;:&quot;https://d.docs.live.net/b669f6a8ed5a07e6/Documents/ESPN/IFTTT.one&quot;},&quot;ViewInBrowserUrl&quot;:{&quot;Href&quot;:&quot;https://onedrive.live.com/redir.aspx?cid=b669f6a8ed5a07e6&amp;page=browse&amp;resid=B669F6A8ED5A07E6!17 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MyJson {
            get {
                return ResourceManager.GetString("MyJson", resourceCulture);
            }
        }
    }
}
